### ISSUE TITLE
Retrieve CNRFC raw observations for river forecast points

### ISSUE THREAD

**Issue by narlesky** [MBKEngineers/collect#62]
### Task
Provide a function in the `collect.cnrfc` module that retrieves the observation timeseries provided for certain CNRFC locations.  Observed flow timeseries details pages are available via this URL format:
```python
cnrfc_id = 'POHC1'
url = f'https://www.cnrfc.noaa.gov/obsRiver_hc.php?id={cnrfc_id}'
```

### Steps
- [ ] Provide a method to download and convert observation timeseries data to a dataframe
- [ ] Possibly provide a method to include any metadata associated with the record
- [ ] Determine subset of forecast locations and possibly provide a method `get_observed_record_forecast_locations`
- [ ] Develop testing methods for the new functions

### Breaking Changes
None expected

### Priority
Medium
